Implemented YMODEM for embedded target
shymega/txmodems pull request #1
Opened 2024-06-06 13:59 UTC by ejka-inapril

removed std and alloc dependencies from ymodem

2024-06-06 14:20 UTC, shymega commented
Thank you, but there's too many changes in this PR unrelated to the PR title. Also, did you mean to close the PR?

2024-06-06 14:20 UTC, shymega commented
I would rather have smaller, composable PRs addressing each change, with commits describing the change.

2024-06-06 14:58 UTC, shymega requested changes
Several changes needed, and if you can open other PRs to address this, that would be great, and we can close this one as the parent PR.

2024-06-06 14:58 UTC, shymega commented on Cargo.toml
> +repository = "https://github.com/inApril-AS/txmodems"
I would rather this wasn't changed. It looks like you want to rebrand my crate as your own, which isn't fair to my work, and the derived code from other crates.

2024-06-06 14:58 UTC, shymega commented on Cargo.toml
> +]
Version bump is fine, and keywords are fine - but you should be asking before adding yourselves to the authors key. I was going to put 'The Cosmo-CoDiOS Developers' at some point, given this project is under that umbrella.

2024-06-06 14:58 UTC, shymega commented on Cargo.toml
> -default = []
Good catch. LGTM.

2024-06-06 14:58 UTC, shymega commented on Cargo.toml
> +heapless = "0.8.0"
Why do we need this?

2024-06-06 14:58 UTC, shymega commented on Cargo.toml
> +defmt = { version = "0.3", optional = true }
Ah, good catch for logging on embedded.

2024-06-06 14:58 UTC, shymega commented on src/common.rs
Again, need justification for using `heapless`. I was trying to reduce the amount of external deps.

2024-06-06 14:58 UTC, shymega commented on src/common.rs
>  }
Not very informative docstrings. Seems hastily done.

2024-06-06 14:58 UTC, shymega commented on src/common.rs
> +    },
I'm not sure why this has been changed to be like this.

2024-06-06 14:58 UTC, shymega commented on src/common.rs
> +/// Modem Result type
Should include details on `T` and `E` in docstring.

2024-06-06 14:58 UTC, shymega commented on src/common.rs
> +    /// Return a new instance of the `modem` struct.
Should be `Modem`.

2024-06-06 14:58 UTC, shymega commented on src/common.rs
> +    /// get byte
docstrings should include return types, and descriptions of params.

2024-06-06 14:58 UTC, shymega commented on src/variants/mod.rs
>      //! Disabled by default.
Good catch!

2024-06-06 14:58 UTC, shymega commented on src/variants/api/ymodem.rs
> +        debug!("First byte recieved. Sendiong start frame.");
Typo.

2024-06-06 14:58 UTC, shymega commented on src/variants/api/ymodem.rs
> +        debug!("Start frame acknowleded. Sending stream");
Typo.

2024-06-06 14:58 UTC, shymega commented on src/variants/api/ymodem.rs
> +const CRC: u8 = 0x43;
Why not use `crate::ymodem::Consts`? That was written specifically to avoid single-line consts. Please adjust.

2024-06-06 14:58 UTC, shymega commented on src/common.rs
> +        file_name: String<32>,
Typo?

2024-06-06 14:58 UTC, shymega commented on src/lib.rs
>  pub mod variants;
`common` should remain private!

2024-06-06 14:58 UTC, shymega commented on src/variants/api/ymodem.rs
>      pub max_initial_errors: u32,
Please refrain from unnecessary newlines.

2024-06-06 14:58 UTC, shymega commented on src/variants/api/ymodem.rs
> +        }
This branch can be simplified. Remove `else` and simply end function with `Ok(())`.

2024-06-07 10:24 UTC, ejka-inapril commented
> did you mean to close the PR?

Yes, I didn't mean to open it.

2024-11-13 09:51 UTC, closed without merging

2024-11-14 08:30 UTC, shymega commented
Hi,

Why was this PR closed? 

I would like to have your changes upstreamed - I saw briefly on your
fork that you have implemented `embedded-io-async` support, and this is
very promising.

Whilst I can't dictate that you upstream the changes, as the license
isn't copyleft, I would be very open to accepting your changes, and
working on a fully open-source implementation.

On 13.11.2024 01:52, inApril-AS wrote:
>Closed #1.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/Cosmo-CoDiOS/txmodems/pull/1#event-15279831497
>You are receiving this because you were assigned.
>
>Message ID: ***@***.***>
Best wishes,
--
Dom Rodriguez

2024-11-14 09:55 UTC, ejka-inapril commented
Hi,

The PR was automatically closed since I made the repository private.
I did this because I thought the changes strayed to far from the original crate, and I was unsure of my employers take on it being open source.
But since you are interested, and I got a yes from my employer I can reopen new issues on a new fork.

Eskild J. K. Aanensen

2024-11-15 07:45 UTC, shymega commented
On 14.11.2024 01:56, Eskild Jonatan Krumsvik Aanensen wrote:

>The PR was automatically closed since I made the repository private.
>I did this because I thought the changes strayed to far from the original crate, and I was unsure of my employers take on it being open source.
>But since you are interested, and I got a yes from my employer I can reopen new issues on a new fork.

That's excellent to hear! Please do feel free to open a new fork & PR. I
will then do a review, and try and get it merged in.

I'm going to setup a CI workflow and automatic Dependabot merges as well
at some point.

Do you think it's worth adding CI tests for mocking the YMODEM/XMODEM
implementation streams?

Thank you for your efforts on this front.

Best wishes,
--
Dom Rodriguez

2024-11-18 13:24 UTC, ejka-inapril commented
I have opened a new fork, and will do a PR soon. As I have gotten a prototype working receiving data.

I don't know if adding CI is worth it, I think that would be up to you.

Eskild J. K. Aanensen

2024-12-07 21:40 UTC, shymega commented
Hi,

I've reviewed #2.

As for CI, I was not thinking necessarily of testing real-world data, but just mock tests of 'example' data. We could use the base Modem trait for that.

2024-12-07 21:40 UTC, shymega commented
Feel free to open a PR adding YMODEM support, and your `embedded-io-async` support on InApril's fork.